import { Header } from '@/components/header/Header';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Header />
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                    {children}
                </div>
            </body>
        </html>
    );
}
